// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xla/service/buffer_assignment.proto
// Protobuf C++ Version: 5.29.0

#include "xla/service/buffer_assignment.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace xla {
namespace buffer_assignment {

inline constexpr BufferIsolationConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : isolation_colors_{},
        _isolation_colors_cached_byte_size_{0},
        base_offset_bytes_{::int64_t{0}},
        isolation_fuel_{::int64_t{0}},
        isolation_padding_bytes_{::int64_t{0}},
        isolation_order_salt_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BufferIsolationConfig::BufferIsolationConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BufferIsolationConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BufferIsolationConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BufferIsolationConfigDefaultTypeInternal() {}
  union {
    BufferIsolationConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BufferIsolationConfigDefaultTypeInternal _BufferIsolationConfig_default_instance_;
}  // namespace buffer_assignment
}  // namespace xla
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_xla_2fservice_2fbuffer_5fassignment_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_xla_2fservice_2fbuffer_5fassignment_2eproto = nullptr;
const ::uint32_t
    TableStruct_xla_2fservice_2fbuffer_5fassignment_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::xla::buffer_assignment::BufferIsolationConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::xla::buffer_assignment::BufferIsolationConfig, _impl_.base_offset_bytes_),
        PROTOBUF_FIELD_OFFSET(::xla::buffer_assignment::BufferIsolationConfig, _impl_.isolation_fuel_),
        PROTOBUF_FIELD_OFFSET(::xla::buffer_assignment::BufferIsolationConfig, _impl_.isolation_padding_bytes_),
        PROTOBUF_FIELD_OFFSET(::xla::buffer_assignment::BufferIsolationConfig, _impl_.isolation_order_salt_),
        PROTOBUF_FIELD_OFFSET(::xla::buffer_assignment::BufferIsolationConfig, _impl_.isolation_colors_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::xla::buffer_assignment::BufferIsolationConfig)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::xla::buffer_assignment::_BufferIsolationConfig_default_instance_._instance,
};
const char descriptor_table_protodef_xla_2fservice_2fbuffer_5fassignment_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n#xla/service/buffer_assignment.proto\022\025x"
    "la.buffer_assignment\"\243\001\n\025BufferIsolation"
    "Config\022\031\n\021base_offset_bytes\030\001 \001(\003\022\026\n\016iso"
    "lation_fuel\030\002 \001(\003\022\037\n\027isolation_padding_b"
    "ytes\030\003 \001(\003\022\034\n\024isolation_order_salt\030\004 \001(\004"
    "\022\030\n\020isolation_colors\030\005 \003(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_xla_2fservice_2fbuffer_5fassignment_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_xla_2fservice_2fbuffer_5fassignment_2eproto = {
    false,
    false,
    234,
    descriptor_table_protodef_xla_2fservice_2fbuffer_5fassignment_2eproto,
    "xla/service/buffer_assignment.proto",
    &descriptor_table_xla_2fservice_2fbuffer_5fassignment_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_xla_2fservice_2fbuffer_5fassignment_2eproto::offsets,
    file_level_enum_descriptors_xla_2fservice_2fbuffer_5fassignment_2eproto,
    file_level_service_descriptors_xla_2fservice_2fbuffer_5fassignment_2eproto,
};
namespace xla {
namespace buffer_assignment {
// ===================================================================

class BufferIsolationConfig::_Internal {
 public:
};

BufferIsolationConfig::BufferIsolationConfig(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xla.buffer_assignment.BufferIsolationConfig)
}
inline PROTOBUF_NDEBUG_INLINE BufferIsolationConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::xla::buffer_assignment::BufferIsolationConfig& from_msg)
      : isolation_colors_{visibility, arena, from.isolation_colors_},
        _isolation_colors_cached_byte_size_{0},
        _cached_size_{0} {}

BufferIsolationConfig::BufferIsolationConfig(
    ::google::protobuf::Arena* arena,
    const BufferIsolationConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BufferIsolationConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, base_offset_bytes_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, base_offset_bytes_),
           offsetof(Impl_, isolation_order_salt_) -
               offsetof(Impl_, base_offset_bytes_) +
               sizeof(Impl_::isolation_order_salt_));

  // @@protoc_insertion_point(copy_constructor:xla.buffer_assignment.BufferIsolationConfig)
}
inline PROTOBUF_NDEBUG_INLINE BufferIsolationConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : isolation_colors_{visibility, arena},
        _isolation_colors_cached_byte_size_{0},
        _cached_size_{0} {}

inline void BufferIsolationConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, base_offset_bytes_),
           0,
           offsetof(Impl_, isolation_order_salt_) -
               offsetof(Impl_, base_offset_bytes_) +
               sizeof(Impl_::isolation_order_salt_));
}
BufferIsolationConfig::~BufferIsolationConfig() {
  // @@protoc_insertion_point(destructor:xla.buffer_assignment.BufferIsolationConfig)
  SharedDtor(*this);
}
inline void BufferIsolationConfig::SharedDtor(MessageLite& self) {
  BufferIsolationConfig& this_ = static_cast<BufferIsolationConfig&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BufferIsolationConfig::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BufferIsolationConfig(arena);
}
constexpr auto BufferIsolationConfig::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_colors_) +
          decltype(BufferIsolationConfig::_impl_.isolation_colors_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(BufferIsolationConfig), alignof(BufferIsolationConfig), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BufferIsolationConfig::PlacementNew_,
                                 sizeof(BufferIsolationConfig),
                                 alignof(BufferIsolationConfig));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BufferIsolationConfig::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BufferIsolationConfig_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BufferIsolationConfig::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BufferIsolationConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BufferIsolationConfig::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BufferIsolationConfig>(), &BufferIsolationConfig::ByteSizeLong,
            &BufferIsolationConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_._cached_size_),
        false,
    },
    &BufferIsolationConfig::kDescriptorMethods,
    &descriptor_table_xla_2fservice_2fbuffer_5fassignment_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BufferIsolationConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2> BufferIsolationConfig::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::xla::buffer_assignment::BufferIsolationConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 base_offset_bytes = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BufferIsolationConfig, _impl_.base_offset_bytes_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.base_offset_bytes_)}},
    // int64 isolation_fuel = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BufferIsolationConfig, _impl_.isolation_fuel_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_fuel_)}},
    // int64 isolation_padding_bytes = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BufferIsolationConfig, _impl_.isolation_padding_bytes_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_padding_bytes_)}},
    // uint64 isolation_order_salt = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BufferIsolationConfig, _impl_.isolation_order_salt_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_order_salt_)}},
    // repeated int32 isolation_colors = 5;
    {::_pbi::TcParser::FastV32P1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_colors_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 base_offset_bytes = 1;
    {PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.base_offset_bytes_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 isolation_fuel = 2;
    {PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_fuel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 isolation_padding_bytes = 3;
    {PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_padding_bytes_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // uint64 isolation_order_salt = 4;
    {PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_order_salt_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // repeated int32 isolation_colors = 5;
    {PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_colors_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void BufferIsolationConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:xla.buffer_assignment.BufferIsolationConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.isolation_colors_.Clear();
  ::memset(&_impl_.base_offset_bytes_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.isolation_order_salt_) -
      reinterpret_cast<char*>(&_impl_.base_offset_bytes_)) + sizeof(_impl_.isolation_order_salt_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BufferIsolationConfig::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BufferIsolationConfig& this_ = static_cast<const BufferIsolationConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BufferIsolationConfig::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BufferIsolationConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:xla.buffer_assignment.BufferIsolationConfig)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 base_offset_bytes = 1;
          if (this_._internal_base_offset_bytes() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_base_offset_bytes(), target);
          }

          // int64 isolation_fuel = 2;
          if (this_._internal_isolation_fuel() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_isolation_fuel(), target);
          }

          // int64 isolation_padding_bytes = 3;
          if (this_._internal_isolation_padding_bytes() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<3>(
                    stream, this_._internal_isolation_padding_bytes(), target);
          }

          // uint64 isolation_order_salt = 4;
          if (this_._internal_isolation_order_salt() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                4, this_._internal_isolation_order_salt(), target);
          }

          // repeated int32 isolation_colors = 5;
          {
            int byte_size = this_._impl_._isolation_colors_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  5, this_._internal_isolation_colors(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:xla.buffer_assignment.BufferIsolationConfig)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BufferIsolationConfig::ByteSizeLong(const MessageLite& base) {
          const BufferIsolationConfig& this_ = static_cast<const BufferIsolationConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BufferIsolationConfig::ByteSizeLong() const {
          const BufferIsolationConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:xla.buffer_assignment.BufferIsolationConfig)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 isolation_colors = 5;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_isolation_colors(), 1,
                      this_._impl_._isolation_colors_cached_byte_size_);
            }
          }
           {
            // int64 base_offset_bytes = 1;
            if (this_._internal_base_offset_bytes() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_base_offset_bytes());
            }
            // int64 isolation_fuel = 2;
            if (this_._internal_isolation_fuel() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_isolation_fuel());
            }
            // int64 isolation_padding_bytes = 3;
            if (this_._internal_isolation_padding_bytes() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_isolation_padding_bytes());
            }
            // uint64 isolation_order_salt = 4;
            if (this_._internal_isolation_order_salt() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_isolation_order_salt());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BufferIsolationConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BufferIsolationConfig*>(&to_msg);
  auto& from = static_cast<const BufferIsolationConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xla.buffer_assignment.BufferIsolationConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_isolation_colors()->MergeFrom(from._internal_isolation_colors());
  if (from._internal_base_offset_bytes() != 0) {
    _this->_impl_.base_offset_bytes_ = from._impl_.base_offset_bytes_;
  }
  if (from._internal_isolation_fuel() != 0) {
    _this->_impl_.isolation_fuel_ = from._impl_.isolation_fuel_;
  }
  if (from._internal_isolation_padding_bytes() != 0) {
    _this->_impl_.isolation_padding_bytes_ = from._impl_.isolation_padding_bytes_;
  }
  if (from._internal_isolation_order_salt() != 0) {
    _this->_impl_.isolation_order_salt_ = from._impl_.isolation_order_salt_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BufferIsolationConfig::CopyFrom(const BufferIsolationConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xla.buffer_assignment.BufferIsolationConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BufferIsolationConfig::InternalSwap(BufferIsolationConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.isolation_colors_.InternalSwap(&other->_impl_.isolation_colors_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.isolation_order_salt_)
      + sizeof(BufferIsolationConfig::_impl_.isolation_order_salt_)
      - PROTOBUF_FIELD_OFFSET(BufferIsolationConfig, _impl_.base_offset_bytes_)>(
          reinterpret_cast<char*>(&_impl_.base_offset_bytes_),
          reinterpret_cast<char*>(&other->_impl_.base_offset_bytes_));
}

::google::protobuf::Metadata BufferIsolationConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace buffer_assignment
}  // namespace xla
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_xla_2fservice_2fbuffer_5fassignment_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
