// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xla/service/metrics.proto
// Protobuf C++ Version: 5.29.0

#include "xla/service/metrics.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace xla {

inline constexpr JobInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cell_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        user_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        uid_{::int64_t{0}},
        task_id_{::int64_t{0}},
        task_uid_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR JobInfo::JobInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JobInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JobInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JobInfoDefaultTypeInternal() {}
  union {
    JobInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JobInfoDefaultTypeInternal _JobInfo_default_instance_;

inline constexpr PassMetrics::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pass_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pass_duration_{nullptr},
        custom_metrics_{nullptr},
        module_id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR PassMetrics::PassMetrics(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PassMetricsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PassMetricsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PassMetricsDefaultTypeInternal() {}
  union {
    PassMetrics _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PassMetricsDefaultTypeInternal _PassMetrics_default_instance_;

inline constexpr CompilationLogEntry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pass_metrics_{},
        module_ids_{},
        _module_ids_cached_byte_size_{0},
        timestamp_{nullptr},
        duration_{nullptr},
        job_info_{nullptr},
        stage_{static_cast< ::xla::CompilationLogEntry_CompilationStage >(0)},
        task_index_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CompilationLogEntry::CompilationLogEntry(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CompilationLogEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CompilationLogEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CompilationLogEntryDefaultTypeInternal() {}
  union {
    CompilationLogEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CompilationLogEntryDefaultTypeInternal _CompilationLogEntry_default_instance_;
}  // namespace xla
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_xla_2fservice_2fmetrics_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_xla_2fservice_2fmetrics_2eproto = nullptr;
const ::uint32_t
    TableStruct_xla_2fservice_2fmetrics_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::xla::PassMetrics, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::xla::PassMetrics, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::xla::PassMetrics, _impl_.module_id_),
        PROTOBUF_FIELD_OFFSET(::xla::PassMetrics, _impl_.pass_name_),
        PROTOBUF_FIELD_OFFSET(::xla::PassMetrics, _impl_.pass_duration_),
        PROTOBUF_FIELD_OFFSET(::xla::PassMetrics, _impl_.custom_metrics_),
        ~0u,
        ~0u,
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::xla::JobInfo, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::xla::JobInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::xla::JobInfo, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::xla::JobInfo, _impl_.cell_),
        PROTOBUF_FIELD_OFFSET(::xla::JobInfo, _impl_.user_),
        PROTOBUF_FIELD_OFFSET(::xla::JobInfo, _impl_.uid_),
        PROTOBUF_FIELD_OFFSET(::xla::JobInfo, _impl_.task_id_),
        PROTOBUF_FIELD_OFFSET(::xla::JobInfo, _impl_.task_uid_),
        0,
        1,
        2,
        3,
        4,
        5,
        PROTOBUF_FIELD_OFFSET(::xla::CompilationLogEntry, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::xla::CompilationLogEntry, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::xla::CompilationLogEntry, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::xla::CompilationLogEntry, _impl_.stage_),
        PROTOBUF_FIELD_OFFSET(::xla::CompilationLogEntry, _impl_.duration_),
        PROTOBUF_FIELD_OFFSET(::xla::CompilationLogEntry, _impl_.task_index_),
        PROTOBUF_FIELD_OFFSET(::xla::CompilationLogEntry, _impl_.pass_metrics_),
        PROTOBUF_FIELD_OFFSET(::xla::CompilationLogEntry, _impl_.module_ids_),
        PROTOBUF_FIELD_OFFSET(::xla::CompilationLogEntry, _impl_.job_info_),
        0,
        ~0u,
        1,
        ~0u,
        ~0u,
        ~0u,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::xla::PassMetrics)},
        {16, 30, -1, sizeof(::xla::JobInfo)},
        {36, 51, -1, sizeof(::xla::CompilationLogEntry)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::xla::_PassMetrics_default_instance_._instance,
    &::xla::_JobInfo_default_instance_._instance,
    &::xla::_CompilationLogEntry_default_instance_._instance,
};
const char descriptor_table_protodef_xla_2fservice_2fmetrics_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031xla/service/metrics.proto\022\003xla\032\031google"
    "/protobuf/any.proto\032\036google/protobuf/dur"
    "ation.proto\032\037google/protobuf/timestamp.p"
    "roto\"\223\001\n\013PassMetrics\022\021\n\tmodule_id\030\001 \001(\004\022"
    "\021\n\tpass_name\030\002 \001(\t\0220\n\rpass_duration\030\003 \001("
    "\0132\031.google.protobuf.Duration\022,\n\016custom_m"
    "etrics\030\004 \001(\0132\024.google.protobuf.Any\"\275\001\n\007J"
    "obInfo\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\021\n\004cell\030\002 \001(\tH"
    "\001\210\001\001\022\021\n\004user\030\003 \001(\tH\002\210\001\001\022\020\n\003uid\030\004 \001(\003H\003\210\001"
    "\001\022\024\n\007task_id\030\005 \001(\003H\004\210\001\001\022\025\n\010task_uid\030\006 \001("
    "\003H\005\210\001\001B\007\n\005_nameB\007\n\005_cellB\007\n\005_userB\006\n\004_ui"
    "dB\n\n\010_task_idB\013\n\t_task_uid\"\211\003\n\023Compilati"
    "onLogEntry\022-\n\ttimestamp\030\001 \001(\0132\032.google.p"
    "rotobuf.Timestamp\0228\n\005stage\030\002 \001(\0162).xla.C"
    "ompilationLogEntry.CompilationStage\022+\n\010d"
    "uration\030\003 \001(\0132\031.google.protobuf.Duration"
    "\022\022\n\ntask_index\030\004 \001(\005\022&\n\014pass_metrics\030\005 \003"
    "(\0132\020.xla.PassMetrics\022\022\n\nmodule_ids\030\006 \003(\004"
    "\022\036\n\010job_info\030\007 \001(\0132\014.xla.JobInfo\"l\n\020Comp"
    "ilationStage\022\017\n\013UNSPECIFIED\020\000\022\016\n\nEND_TO_"
    "END\020\001\022\016\n\nHLO_PASSES\020\002\022\023\n\017CODE_GENERATION"
    "\020\003\022\022\n\016BACKEND_PASSES\020\004b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_xla_2fservice_2fmetrics_2eproto_deps[3] =
    {
        &::descriptor_table_google_2fprotobuf_2fany_2eproto,
        &::descriptor_table_google_2fprotobuf_2fduration_2eproto,
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_xla_2fservice_2fmetrics_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_xla_2fservice_2fmetrics_2eproto = {
    false,
    false,
    870,
    descriptor_table_protodef_xla_2fservice_2fmetrics_2eproto,
    "xla/service/metrics.proto",
    &descriptor_table_xla_2fservice_2fmetrics_2eproto_once,
    descriptor_table_xla_2fservice_2fmetrics_2eproto_deps,
    3,
    3,
    schemas,
    file_default_instances,
    TableStruct_xla_2fservice_2fmetrics_2eproto::offsets,
    file_level_enum_descriptors_xla_2fservice_2fmetrics_2eproto,
    file_level_service_descriptors_xla_2fservice_2fmetrics_2eproto,
};
namespace xla {
const ::google::protobuf::EnumDescriptor* CompilationLogEntry_CompilationStage_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_xla_2fservice_2fmetrics_2eproto);
  return file_level_enum_descriptors_xla_2fservice_2fmetrics_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CompilationLogEntry_CompilationStage_internal_data_[] = {
    327680u, 0u, };
bool CompilationLogEntry_CompilationStage_IsValid(int value) {
  return 0 <= value && value <= 4;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr CompilationLogEntry_CompilationStage CompilationLogEntry::UNSPECIFIED;
constexpr CompilationLogEntry_CompilationStage CompilationLogEntry::END_TO_END;
constexpr CompilationLogEntry_CompilationStage CompilationLogEntry::HLO_PASSES;
constexpr CompilationLogEntry_CompilationStage CompilationLogEntry::CODE_GENERATION;
constexpr CompilationLogEntry_CompilationStage CompilationLogEntry::BACKEND_PASSES;
constexpr CompilationLogEntry_CompilationStage CompilationLogEntry::CompilationStage_MIN;
constexpr CompilationLogEntry_CompilationStage CompilationLogEntry::CompilationStage_MAX;
constexpr int CompilationLogEntry::CompilationStage_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class PassMetrics::_Internal {
 public:
  using HasBits =
      decltype(std::declval<PassMetrics>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_._has_bits_);
};

void PassMetrics::clear_pass_duration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pass_duration_ != nullptr) _impl_.pass_duration_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void PassMetrics::clear_custom_metrics() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.custom_metrics_ != nullptr) _impl_.custom_metrics_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
PassMetrics::PassMetrics(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xla.PassMetrics)
}
inline PROTOBUF_NDEBUG_INLINE PassMetrics::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::xla::PassMetrics& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pass_name_(arena, from.pass_name_) {}

PassMetrics::PassMetrics(
    ::google::protobuf::Arena* arena,
    const PassMetrics& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PassMetrics* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.pass_duration_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(
                              arena, *from._impl_.pass_duration_)
                        : nullptr;
  _impl_.custom_metrics_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Any>(
                              arena, *from._impl_.custom_metrics_)
                        : nullptr;
  _impl_.module_id_ = from._impl_.module_id_;

  // @@protoc_insertion_point(copy_constructor:xla.PassMetrics)
}
inline PROTOBUF_NDEBUG_INLINE PassMetrics::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pass_name_(arena) {}

inline void PassMetrics::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pass_duration_),
           0,
           offsetof(Impl_, module_id_) -
               offsetof(Impl_, pass_duration_) +
               sizeof(Impl_::module_id_));
}
PassMetrics::~PassMetrics() {
  // @@protoc_insertion_point(destructor:xla.PassMetrics)
  SharedDtor(*this);
}
inline void PassMetrics::SharedDtor(MessageLite& self) {
  PassMetrics& this_ = static_cast<PassMetrics&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.pass_name_.Destroy();
  delete this_._impl_.pass_duration_;
  delete this_._impl_.custom_metrics_;
  this_._impl_.~Impl_();
}

inline void* PassMetrics::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PassMetrics(arena);
}
constexpr auto PassMetrics::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PassMetrics),
                                            alignof(PassMetrics));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PassMetrics::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PassMetrics_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PassMetrics::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PassMetrics>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PassMetrics::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PassMetrics>(), &PassMetrics::ByteSizeLong,
            &PassMetrics::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_._cached_size_),
        false,
    },
    &PassMetrics::kDescriptorMethods,
    &descriptor_table_xla_2fservice_2fmetrics_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PassMetrics::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 33, 2> PassMetrics::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::xla::PassMetrics>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .google.protobuf.Any custom_metrics = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 1, PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.custom_metrics_)}},
    // uint64 module_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PassMetrics, _impl_.module_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.module_id_)}},
    // string pass_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.pass_name_)}},
    // .google.protobuf.Duration pass_duration = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.pass_duration_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 module_id = 1;
    {PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.module_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string pass_name = 2;
    {PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.pass_name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Duration pass_duration = 3;
    {PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.pass_duration_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Any custom_metrics = 4;
    {PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.custom_metrics_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Duration>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
  }}, {{
    "\17\0\11\0\0\0\0\0"
    "xla.PassMetrics"
    "pass_name"
  }},
};

PROTOBUF_NOINLINE void PassMetrics::Clear() {
// @@protoc_insertion_point(message_clear_start:xla.PassMetrics)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pass_name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.pass_duration_ != nullptr);
      _impl_.pass_duration_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.custom_metrics_ != nullptr);
      _impl_.custom_metrics_->Clear();
    }
  }
  _impl_.module_id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PassMetrics::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PassMetrics& this_ = static_cast<const PassMetrics&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PassMetrics::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PassMetrics& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:xla.PassMetrics)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 module_id = 1;
          if (this_._internal_module_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_module_id(), target);
          }

          // string pass_name = 2;
          if (!this_._internal_pass_name().empty()) {
            const std::string& _s = this_._internal_pass_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xla.PassMetrics.pass_name");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .google.protobuf.Duration pass_duration = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.pass_duration_, this_._impl_.pass_duration_->GetCachedSize(), target,
                stream);
          }

          // .google.protobuf.Any custom_metrics = 4;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                4, *this_._impl_.custom_metrics_, this_._impl_.custom_metrics_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:xla.PassMetrics)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PassMetrics::ByteSizeLong(const MessageLite& base) {
          const PassMetrics& this_ = static_cast<const PassMetrics&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PassMetrics::ByteSizeLong() const {
          const PassMetrics& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:xla.PassMetrics)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string pass_name = 2;
            if (!this_._internal_pass_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_pass_name());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .google.protobuf.Duration pass_duration = 3;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.pass_duration_);
            }
            // .google.protobuf.Any custom_metrics = 4;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.custom_metrics_);
            }
          }
           {
            // uint64 module_id = 1;
            if (this_._internal_module_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_module_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PassMetrics::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PassMetrics*>(&to_msg);
  auto& from = static_cast<const PassMetrics&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:xla.PassMetrics)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_pass_name().empty()) {
    _this->_internal_set_pass_name(from._internal_pass_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.pass_duration_ != nullptr);
      if (_this->_impl_.pass_duration_ == nullptr) {
        _this->_impl_.pass_duration_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(arena, *from._impl_.pass_duration_);
      } else {
        _this->_impl_.pass_duration_->MergeFrom(*from._impl_.pass_duration_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.custom_metrics_ != nullptr);
      if (_this->_impl_.custom_metrics_ == nullptr) {
        _this->_impl_.custom_metrics_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Any>(arena, *from._impl_.custom_metrics_);
      } else {
        _this->_impl_.custom_metrics_->MergeFrom(*from._impl_.custom_metrics_);
      }
    }
  }
  if (from._internal_module_id() != 0) {
    _this->_impl_.module_id_ = from._impl_.module_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PassMetrics::CopyFrom(const PassMetrics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xla.PassMetrics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PassMetrics::InternalSwap(PassMetrics* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pass_name_, &other->_impl_.pass_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.module_id_)
      + sizeof(PassMetrics::_impl_.module_id_)
      - PROTOBUF_FIELD_OFFSET(PassMetrics, _impl_.pass_duration_)>(
          reinterpret_cast<char*>(&_impl_.pass_duration_),
          reinterpret_cast<char*>(&other->_impl_.pass_duration_));
}

::google::protobuf::Metadata PassMetrics::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class JobInfo::_Internal {
 public:
  using HasBits =
      decltype(std::declval<JobInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(JobInfo, _impl_._has_bits_);
};

JobInfo::JobInfo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xla.JobInfo)
}
inline PROTOBUF_NDEBUG_INLINE JobInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::xla::JobInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_),
        cell_(arena, from.cell_),
        user_(arena, from.user_) {}

JobInfo::JobInfo(
    ::google::protobuf::Arena* arena,
    const JobInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  JobInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, uid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, uid_),
           offsetof(Impl_, task_uid_) -
               offsetof(Impl_, uid_) +
               sizeof(Impl_::task_uid_));

  // @@protoc_insertion_point(copy_constructor:xla.JobInfo)
}
inline PROTOBUF_NDEBUG_INLINE JobInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena),
        cell_(arena),
        user_(arena) {}

inline void JobInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, uid_),
           0,
           offsetof(Impl_, task_uid_) -
               offsetof(Impl_, uid_) +
               sizeof(Impl_::task_uid_));
}
JobInfo::~JobInfo() {
  // @@protoc_insertion_point(destructor:xla.JobInfo)
  SharedDtor(*this);
}
inline void JobInfo::SharedDtor(MessageLite& self) {
  JobInfo& this_ = static_cast<JobInfo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.cell_.Destroy();
  this_._impl_.user_.Destroy();
  this_._impl_.~Impl_();
}

inline void* JobInfo::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) JobInfo(arena);
}
constexpr auto JobInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(JobInfo),
                                            alignof(JobInfo));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull JobInfo::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_JobInfo_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &JobInfo::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<JobInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &JobInfo::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<JobInfo>(), &JobInfo::ByteSizeLong,
            &JobInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(JobInfo, _impl_._cached_size_),
        false,
    },
    &JobInfo::kDescriptorMethods,
    &descriptor_table_xla_2fservice_2fmetrics_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* JobInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 32, 2> JobInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JobInfo, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::xla::JobInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.name_)}},
    // optional string cell = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.cell_)}},
    // optional string user = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.user_)}},
    // optional int64 uid = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(JobInfo, _impl_.uid_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.uid_)}},
    // optional int64 task_id = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(JobInfo, _impl_.task_id_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.task_id_)}},
    // optional int64 task_uid = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(JobInfo, _impl_.task_uid_), 5>(),
     {48, 5, 0, PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.task_uid_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string name = 1;
    {PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string cell = 2;
    {PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.cell_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string user = 3;
    {PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.user_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int64 uid = 4;
    {PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.uid_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 task_id = 5;
    {PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.task_id_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 task_uid = 6;
    {PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.task_uid_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\13\4\4\4\0\0\0\0"
    "xla.JobInfo"
    "name"
    "cell"
    "user"
  }},
};

PROTOBUF_NOINLINE void JobInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:xla.JobInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.cell_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.user_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000038u) {
    ::memset(&_impl_.uid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.task_uid_) -
        reinterpret_cast<char*>(&_impl_.uid_)) + sizeof(_impl_.task_uid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* JobInfo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const JobInfo& this_ = static_cast<const JobInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* JobInfo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const JobInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:xla.JobInfo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string name = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xla.JobInfo.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // optional string cell = 2;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_cell();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xla.JobInfo.cell");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // optional string user = 3;
          if (cached_has_bits & 0x00000004u) {
            const std::string& _s = this_._internal_user();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xla.JobInfo.user");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // optional int64 uid = 4;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<4>(
                    stream, this_._internal_uid(), target);
          }

          // optional int64 task_id = 5;
          if (cached_has_bits & 0x00000010u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<5>(
                    stream, this_._internal_task_id(), target);
          }

          // optional int64 task_uid = 6;
          if (cached_has_bits & 0x00000020u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<6>(
                    stream, this_._internal_task_uid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:xla.JobInfo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t JobInfo::ByteSizeLong(const MessageLite& base) {
          const JobInfo& this_ = static_cast<const JobInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t JobInfo::ByteSizeLong() const {
          const JobInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:xla.JobInfo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x0000003fu) {
            // optional string name = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // optional string cell = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_cell());
            }
            // optional string user = 3;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_user());
            }
            // optional int64 uid = 4;
            if (cached_has_bits & 0x00000008u) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_uid());
            }
            // optional int64 task_id = 5;
            if (cached_has_bits & 0x00000010u) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_task_id());
            }
            // optional int64 task_uid = 6;
            if (cached_has_bits & 0x00000020u) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_task_uid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void JobInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JobInfo*>(&to_msg);
  auto& from = static_cast<const JobInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xla.JobInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_cell(from._internal_cell());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_user(from._internal_user());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.uid_ = from._impl_.uid_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.task_id_ = from._impl_.task_id_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.task_uid_ = from._impl_.task_uid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JobInfo::CopyFrom(const JobInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xla.JobInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JobInfo::InternalSwap(JobInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cell_, &other->_impl_.cell_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_, &other->_impl_.user_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.task_uid_)
      + sizeof(JobInfo::_impl_.task_uid_)
      - PROTOBUF_FIELD_OFFSET(JobInfo, _impl_.uid_)>(
          reinterpret_cast<char*>(&_impl_.uid_),
          reinterpret_cast<char*>(&other->_impl_.uid_));
}

::google::protobuf::Metadata JobInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CompilationLogEntry::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CompilationLogEntry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_._has_bits_);
};

void CompilationLogEntry::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void CompilationLogEntry::clear_duration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.duration_ != nullptr) _impl_.duration_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
CompilationLogEntry::CompilationLogEntry(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xla.CompilationLogEntry)
}
inline PROTOBUF_NDEBUG_INLINE CompilationLogEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::xla::CompilationLogEntry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pass_metrics_{visibility, arena, from.pass_metrics_},
        module_ids_{visibility, arena, from.module_ids_},
        _module_ids_cached_byte_size_{0} {}

CompilationLogEntry::CompilationLogEntry(
    ::google::protobuf::Arena* arena,
    const CompilationLogEntry& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CompilationLogEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.timestamp_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.timestamp_)
                        : nullptr;
  _impl_.duration_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(
                              arena, *from._impl_.duration_)
                        : nullptr;
  _impl_.job_info_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::xla::JobInfo>(
                              arena, *from._impl_.job_info_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, stage_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, stage_),
           offsetof(Impl_, task_index_) -
               offsetof(Impl_, stage_) +
               sizeof(Impl_::task_index_));

  // @@protoc_insertion_point(copy_constructor:xla.CompilationLogEntry)
}
inline PROTOBUF_NDEBUG_INLINE CompilationLogEntry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pass_metrics_{visibility, arena},
        module_ids_{visibility, arena},
        _module_ids_cached_byte_size_{0} {}

inline void CompilationLogEntry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, task_index_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::task_index_));
}
CompilationLogEntry::~CompilationLogEntry() {
  // @@protoc_insertion_point(destructor:xla.CompilationLogEntry)
  SharedDtor(*this);
}
inline void CompilationLogEntry::SharedDtor(MessageLite& self) {
  CompilationLogEntry& this_ = static_cast<CompilationLogEntry&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.timestamp_;
  delete this_._impl_.duration_;
  delete this_._impl_.job_info_;
  this_._impl_.~Impl_();
}

inline void* CompilationLogEntry::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CompilationLogEntry(arena);
}
constexpr auto CompilationLogEntry::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.pass_metrics_) +
          decltype(CompilationLogEntry::_impl_.pass_metrics_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.module_ids_) +
          decltype(CompilationLogEntry::_impl_.module_ids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(CompilationLogEntry), alignof(CompilationLogEntry), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CompilationLogEntry::PlacementNew_,
                                 sizeof(CompilationLogEntry),
                                 alignof(CompilationLogEntry));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CompilationLogEntry::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CompilationLogEntry_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CompilationLogEntry::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CompilationLogEntry>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CompilationLogEntry::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CompilationLogEntry>(), &CompilationLogEntry::ByteSizeLong,
            &CompilationLogEntry::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_._cached_size_),
        false,
    },
    &CompilationLogEntry::kDescriptorMethods,
    &descriptor_table_xla_2fservice_2fmetrics_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CompilationLogEntry::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 4, 0, 2> CompilationLogEntry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::xla::CompilationLogEntry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .google.protobuf.Timestamp timestamp = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.timestamp_)}},
    // .xla.CompilationLogEntry.CompilationStage stage = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CompilationLogEntry, _impl_.stage_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.stage_)}},
    // .google.protobuf.Duration duration = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.duration_)}},
    // int32 task_index = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CompilationLogEntry, _impl_.task_index_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.task_index_)}},
    // repeated .xla.PassMetrics pass_metrics = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 2, PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.pass_metrics_)}},
    // repeated uint64 module_ids = 6;
    {::_pbi::TcParser::FastV64P1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.module_ids_)}},
    // .xla.JobInfo job_info = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 2, 3, PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.job_info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Timestamp timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .xla.CompilationLogEntry.CompilationStage stage = 2;
    {PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.stage_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .google.protobuf.Duration duration = 3;
    {PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.duration_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 task_index = 4;
    {PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.task_index_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .xla.PassMetrics pass_metrics = 5;
    {PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.pass_metrics_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated uint64 module_ids = 6;
    {PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.module_ids_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt64)},
    // .xla.JobInfo job_info = 7;
    {PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.job_info_), _Internal::kHasBitsOffset + 2, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Duration>()},
    {::_pbi::TcParser::GetTable<::xla::PassMetrics>()},
    {::_pbi::TcParser::GetTable<::xla::JobInfo>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void CompilationLogEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:xla.CompilationLogEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pass_metrics_.Clear();
  _impl_.module_ids_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.timestamp_ != nullptr);
      _impl_.timestamp_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.duration_ != nullptr);
      _impl_.duration_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.job_info_ != nullptr);
      _impl_.job_info_->Clear();
    }
  }
  ::memset(&_impl_.stage_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.task_index_) -
      reinterpret_cast<char*>(&_impl_.stage_)) + sizeof(_impl_.task_index_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CompilationLogEntry::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CompilationLogEntry& this_ = static_cast<const CompilationLogEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CompilationLogEntry::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CompilationLogEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:xla.CompilationLogEntry)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .google.protobuf.Timestamp timestamp = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.timestamp_, this_._impl_.timestamp_->GetCachedSize(), target,
                stream);
          }

          // .xla.CompilationLogEntry.CompilationStage stage = 2;
          if (this_._internal_stage() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_stage(), target);
          }

          // .google.protobuf.Duration duration = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.duration_, this_._impl_.duration_->GetCachedSize(), target,
                stream);
          }

          // int32 task_index = 4;
          if (this_._internal_task_index() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_task_index(), target);
          }

          // repeated .xla.PassMetrics pass_metrics = 5;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_pass_metrics_size());
               i < n; i++) {
            const auto& repfield = this_._internal_pass_metrics().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    5, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated uint64 module_ids = 6;
          {
            int byte_size = this_._impl_._module_ids_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteUInt64Packed(
                  6, this_._internal_module_ids(), byte_size, target);
            }
          }

          // .xla.JobInfo job_info = 7;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                7, *this_._impl_.job_info_, this_._impl_.job_info_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:xla.CompilationLogEntry)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CompilationLogEntry::ByteSizeLong(const MessageLite& base) {
          const CompilationLogEntry& this_ = static_cast<const CompilationLogEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CompilationLogEntry::ByteSizeLong() const {
          const CompilationLogEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:xla.CompilationLogEntry)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .xla.PassMetrics pass_metrics = 5;
            {
              total_size += 1UL * this_._internal_pass_metrics_size();
              for (const auto& msg : this_._internal_pass_metrics()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated uint64 module_ids = 6;
            {
              total_size +=
                  ::_pbi::WireFormatLite::UInt64SizeWithPackedTagSize(
                      this_._internal_module_ids(), 1,
                      this_._impl_._module_ids_cached_byte_size_);
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // .google.protobuf.Timestamp timestamp = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.timestamp_);
            }
            // .google.protobuf.Duration duration = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.duration_);
            }
            // .xla.JobInfo job_info = 7;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.job_info_);
            }
          }
           {
            // .xla.CompilationLogEntry.CompilationStage stage = 2;
            if (this_._internal_stage() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_stage());
            }
            // int32 task_index = 4;
            if (this_._internal_task_index() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_task_index());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CompilationLogEntry::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CompilationLogEntry*>(&to_msg);
  auto& from = static_cast<const CompilationLogEntry&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:xla.CompilationLogEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pass_metrics()->MergeFrom(
      from._internal_pass_metrics());
  _this->_internal_mutable_module_ids()->MergeFrom(from._internal_module_ids());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.timestamp_ != nullptr);
      if (_this->_impl_.timestamp_ == nullptr) {
        _this->_impl_.timestamp_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.timestamp_);
      } else {
        _this->_impl_.timestamp_->MergeFrom(*from._impl_.timestamp_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.duration_ != nullptr);
      if (_this->_impl_.duration_ == nullptr) {
        _this->_impl_.duration_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Duration>(arena, *from._impl_.duration_);
      } else {
        _this->_impl_.duration_->MergeFrom(*from._impl_.duration_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.job_info_ != nullptr);
      if (_this->_impl_.job_info_ == nullptr) {
        _this->_impl_.job_info_ =
            ::google::protobuf::Message::CopyConstruct<::xla::JobInfo>(arena, *from._impl_.job_info_);
      } else {
        _this->_impl_.job_info_->MergeFrom(*from._impl_.job_info_);
      }
    }
  }
  if (from._internal_stage() != 0) {
    _this->_impl_.stage_ = from._impl_.stage_;
  }
  if (from._internal_task_index() != 0) {
    _this->_impl_.task_index_ = from._impl_.task_index_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CompilationLogEntry::CopyFrom(const CompilationLogEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xla.CompilationLogEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CompilationLogEntry::InternalSwap(CompilationLogEntry* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pass_metrics_.InternalSwap(&other->_impl_.pass_metrics_);
  _impl_.module_ids_.InternalSwap(&other->_impl_.module_ids_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.task_index_)
      + sizeof(CompilationLogEntry::_impl_.task_index_)
      - PROTOBUF_FIELD_OFFSET(CompilationLogEntry, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata CompilationLogEntry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace xla
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_xla_2fservice_2fmetrics_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
