// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tensorflow_serving/apis/get_model_status.proto
// Protobuf C++ Version: 5.29.0

#include "tensorflow_serving/apis/get_model_status.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace tensorflow {
namespace serving {

inline constexpr ModelVersionStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        status_{nullptr},
        version_{::int64_t{0}},
        state_{static_cast< ::tensorflow::serving::ModelVersionStatus_State >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR ModelVersionStatus::ModelVersionStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ModelVersionStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ModelVersionStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ModelVersionStatusDefaultTypeInternal() {}
  union {
    ModelVersionStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ModelVersionStatusDefaultTypeInternal _ModelVersionStatus_default_instance_;

inline constexpr GetModelStatusResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : model_version_status_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetModelStatusResponse::GetModelStatusResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetModelStatusResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetModelStatusResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetModelStatusResponseDefaultTypeInternal() {}
  union {
    GetModelStatusResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetModelStatusResponseDefaultTypeInternal _GetModelStatusResponse_default_instance_;

inline constexpr GetModelStatusRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        model_spec_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR GetModelStatusRequest::GetModelStatusRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetModelStatusRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetModelStatusRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetModelStatusRequestDefaultTypeInternal() {}
  union {
    GetModelStatusRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetModelStatusRequestDefaultTypeInternal _GetModelStatusRequest_default_instance_;
}  // namespace serving
}  // namespace tensorflow
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto = nullptr;
const ::uint32_t
    TableStruct_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::GetModelStatusRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::GetModelStatusRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::GetModelStatusRequest, _impl_.model_spec_),
        0,
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::ModelVersionStatus, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::ModelVersionStatus, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::ModelVersionStatus, _impl_.version_),
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::ModelVersionStatus, _impl_.state_),
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::ModelVersionStatus, _impl_.status_),
        ~0u,
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::GetModelStatusResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::tensorflow::serving::GetModelStatusResponse, _impl_.model_version_status_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::tensorflow::serving::GetModelStatusRequest)},
        {10, 21, -1, sizeof(::tensorflow::serving::ModelVersionStatus)},
        {24, -1, -1, sizeof(::tensorflow::serving::GetModelStatusResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::tensorflow::serving::_GetModelStatusRequest_default_instance_._instance,
    &::tensorflow::serving::_ModelVersionStatus_default_instance_._instance,
    &::tensorflow::serving::_GetModelStatusResponse_default_instance_._instance,
};
const char descriptor_table_protodef_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n.tensorflow_serving/apis/get_model_stat"
    "us.proto\022\022tensorflow.serving\032#tensorflow"
    "_serving/apis/model.proto\032$tensorflow_se"
    "rving/apis/status.proto\"J\n\025GetModelStatu"
    "sRequest\0221\n\nmodel_spec\030\001 \001(\0132\035.tensorflo"
    "w.serving.ModelSpec\"\350\001\n\022ModelVersionStat"
    "us\022\017\n\007version\030\001 \001(\003\022;\n\005state\030\002 \001(\0162,.ten"
    "sorflow.serving.ModelVersionStatus.State"
    "\022/\n\006status\030\003 \001(\0132\037.tensorflow.serving.St"
    "atusProto\"S\n\005State\022\013\n\007UNKNOWN\020\000\022\t\n\005START"
    "\020\n\022\013\n\007LOADING\020\024\022\r\n\tAVAILABLE\020\036\022\r\n\tUNLOAD"
    "ING\020(\022\007\n\003END\0202\"t\n\026GetModelStatusResponse"
    "\022Z\n\024model_version_status\030\001 \003(\0132&.tensorf"
    "low.serving.ModelVersionStatusR\024model_ve"
    "rsion_statusB\003\370\001\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto_deps[2] =
    {
        &::descriptor_table_tensorflow_5fserving_2fapis_2fmodel_2eproto,
        &::descriptor_table_tensorflow_5fserving_2fapis_2fstatus_2eproto,
};
static ::absl::once_flag descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto = {
    false,
    false,
    585,
    descriptor_table_protodef_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto,
    "tensorflow_serving/apis/get_model_status.proto",
    &descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto_once,
    descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto_deps,
    2,
    3,
    schemas,
    file_default_instances,
    TableStruct_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto::offsets,
    file_level_enum_descriptors_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto,
    file_level_service_descriptors_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto,
};
namespace tensorflow {
namespace serving {
const ::google::protobuf::EnumDescriptor* ModelVersionStatus_State_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto);
  return file_level_enum_descriptors_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ModelVersionStatus_State_internal_data_[] = {
    65536u, 64u, 537395712u, 131200u, };
bool ModelVersionStatus_State_IsValid(int value) {
  return 0 <= value && value <= 50 && ((1127000493261825u >> value) & 1) != 0;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr ModelVersionStatus_State ModelVersionStatus::UNKNOWN;
constexpr ModelVersionStatus_State ModelVersionStatus::START;
constexpr ModelVersionStatus_State ModelVersionStatus::LOADING;
constexpr ModelVersionStatus_State ModelVersionStatus::AVAILABLE;
constexpr ModelVersionStatus_State ModelVersionStatus::UNLOADING;
constexpr ModelVersionStatus_State ModelVersionStatus::END;
constexpr ModelVersionStatus_State ModelVersionStatus::State_MIN;
constexpr ModelVersionStatus_State ModelVersionStatus::State_MAX;
constexpr int ModelVersionStatus::State_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class GetModelStatusRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<GetModelStatusRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetModelStatusRequest, _impl_._has_bits_);
};

void GetModelStatusRequest::clear_model_spec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.model_spec_ != nullptr) _impl_.model_spec_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
GetModelStatusRequest::GetModelStatusRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.GetModelStatusRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetModelStatusRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::tensorflow::serving::GetModelStatusRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GetModelStatusRequest::GetModelStatusRequest(
    ::google::protobuf::Arena* arena,
    const GetModelStatusRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetModelStatusRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.model_spec_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::tensorflow::serving::ModelSpec>(
                              arena, *from._impl_.model_spec_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.GetModelStatusRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetModelStatusRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetModelStatusRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.model_spec_ = {};
}
GetModelStatusRequest::~GetModelStatusRequest() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.GetModelStatusRequest)
  SharedDtor(*this);
}
inline void GetModelStatusRequest::SharedDtor(MessageLite& self) {
  GetModelStatusRequest& this_ = static_cast<GetModelStatusRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.model_spec_;
  this_._impl_.~Impl_();
}

inline void* GetModelStatusRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetModelStatusRequest(arena);
}
constexpr auto GetModelStatusRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetModelStatusRequest),
                                            alignof(GetModelStatusRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetModelStatusRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetModelStatusRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetModelStatusRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetModelStatusRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetModelStatusRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetModelStatusRequest>(), &GetModelStatusRequest::ByteSizeLong,
            &GetModelStatusRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetModelStatusRequest, _impl_._cached_size_),
        false,
    },
    &GetModelStatusRequest::kDescriptorMethods,
    &descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetModelStatusRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> GetModelStatusRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetModelStatusRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tensorflow::serving::GetModelStatusRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .tensorflow.serving.ModelSpec model_spec = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(GetModelStatusRequest, _impl_.model_spec_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .tensorflow.serving.ModelSpec model_spec = 1;
    {PROTOBUF_FIELD_OFFSET(GetModelStatusRequest, _impl_.model_spec_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::tensorflow::serving::ModelSpec>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GetModelStatusRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.GetModelStatusRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.model_spec_ != nullptr);
    _impl_.model_spec_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetModelStatusRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetModelStatusRequest& this_ = static_cast<const GetModelStatusRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetModelStatusRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetModelStatusRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.GetModelStatusRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .tensorflow.serving.ModelSpec model_spec = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.model_spec_, this_._impl_.model_spec_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.GetModelStatusRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetModelStatusRequest::ByteSizeLong(const MessageLite& base) {
          const GetModelStatusRequest& this_ = static_cast<const GetModelStatusRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetModelStatusRequest::ByteSizeLong() const {
          const GetModelStatusRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.GetModelStatusRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .tensorflow.serving.ModelSpec model_spec = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.model_spec_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetModelStatusRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetModelStatusRequest*>(&to_msg);
  auto& from = static_cast<const GetModelStatusRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.GetModelStatusRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.model_spec_ != nullptr);
    if (_this->_impl_.model_spec_ == nullptr) {
      _this->_impl_.model_spec_ =
          ::google::protobuf::Message::CopyConstruct<::tensorflow::serving::ModelSpec>(arena, *from._impl_.model_spec_);
    } else {
      _this->_impl_.model_spec_->MergeFrom(*from._impl_.model_spec_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetModelStatusRequest::CopyFrom(const GetModelStatusRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.GetModelStatusRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetModelStatusRequest::InternalSwap(GetModelStatusRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.model_spec_, other->_impl_.model_spec_);
}

::google::protobuf::Metadata GetModelStatusRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ModelVersionStatus::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ModelVersionStatus>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_._has_bits_);
};

void ModelVersionStatus::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.status_ != nullptr) _impl_.status_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
ModelVersionStatus::ModelVersionStatus(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.ModelVersionStatus)
}
inline PROTOBUF_NDEBUG_INLINE ModelVersionStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::tensorflow::serving::ModelVersionStatus& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ModelVersionStatus::ModelVersionStatus(
    ::google::protobuf::Arena* arena,
    const ModelVersionStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ModelVersionStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.status_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::tensorflow::serving::StatusProto>(
                              arena, *from._impl_.status_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, version_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, version_),
           offsetof(Impl_, state_) -
               offsetof(Impl_, version_) +
               sizeof(Impl_::state_));

  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.ModelVersionStatus)
}
inline PROTOBUF_NDEBUG_INLINE ModelVersionStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ModelVersionStatus::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           0,
           offsetof(Impl_, state_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::state_));
}
ModelVersionStatus::~ModelVersionStatus() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.ModelVersionStatus)
  SharedDtor(*this);
}
inline void ModelVersionStatus::SharedDtor(MessageLite& self) {
  ModelVersionStatus& this_ = static_cast<ModelVersionStatus&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.status_;
  this_._impl_.~Impl_();
}

inline void* ModelVersionStatus::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ModelVersionStatus(arena);
}
constexpr auto ModelVersionStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ModelVersionStatus),
                                            alignof(ModelVersionStatus));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ModelVersionStatus::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ModelVersionStatus_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ModelVersionStatus::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ModelVersionStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ModelVersionStatus::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ModelVersionStatus>(), &ModelVersionStatus::ByteSizeLong,
            &ModelVersionStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_._cached_size_),
        false,
    },
    &ModelVersionStatus::kDescriptorMethods,
    &descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ModelVersionStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> ModelVersionStatus::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tensorflow::serving::ModelVersionStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ModelVersionStatus, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_.version_)}},
    // .tensorflow.serving.ModelVersionStatus.State state = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ModelVersionStatus, _impl_.state_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_.state_)}},
    // .tensorflow.serving.StatusProto status = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 version = 1;
    {PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_.version_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .tensorflow.serving.ModelVersionStatus.State state = 2;
    {PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_.state_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .tensorflow.serving.StatusProto status = 3;
    {PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_.status_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::tensorflow::serving::StatusProto>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ModelVersionStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.ModelVersionStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.status_ != nullptr);
    _impl_.status_->Clear();
  }
  ::memset(&_impl_.version_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.state_) -
      reinterpret_cast<char*>(&_impl_.version_)) + sizeof(_impl_.state_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ModelVersionStatus::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ModelVersionStatus& this_ = static_cast<const ModelVersionStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ModelVersionStatus::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ModelVersionStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.ModelVersionStatus)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 version = 1;
          if (this_._internal_version() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_version(), target);
          }

          // .tensorflow.serving.ModelVersionStatus.State state = 2;
          if (this_._internal_state() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_state(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .tensorflow.serving.StatusProto status = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.status_, this_._impl_.status_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.ModelVersionStatus)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ModelVersionStatus::ByteSizeLong(const MessageLite& base) {
          const ModelVersionStatus& this_ = static_cast<const ModelVersionStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ModelVersionStatus::ByteSizeLong() const {
          const ModelVersionStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.ModelVersionStatus)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .tensorflow.serving.StatusProto status = 3;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.status_);
            }
          }
           {
            // int64 version = 1;
            if (this_._internal_version() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_version());
            }
            // .tensorflow.serving.ModelVersionStatus.State state = 2;
            if (this_._internal_state() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_state());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ModelVersionStatus::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ModelVersionStatus*>(&to_msg);
  auto& from = static_cast<const ModelVersionStatus&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.ModelVersionStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.status_ != nullptr);
    if (_this->_impl_.status_ == nullptr) {
      _this->_impl_.status_ =
          ::google::protobuf::Message::CopyConstruct<::tensorflow::serving::StatusProto>(arena, *from._impl_.status_);
    } else {
      _this->_impl_.status_->MergeFrom(*from._impl_.status_);
    }
  }
  if (from._internal_version() != 0) {
    _this->_impl_.version_ = from._impl_.version_;
  }
  if (from._internal_state() != 0) {
    _this->_impl_.state_ = from._impl_.state_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ModelVersionStatus::CopyFrom(const ModelVersionStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.ModelVersionStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ModelVersionStatus::InternalSwap(ModelVersionStatus* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_.state_)
      + sizeof(ModelVersionStatus::_impl_.state_)
      - PROTOBUF_FIELD_OFFSET(ModelVersionStatus, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::google::protobuf::Metadata ModelVersionStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetModelStatusResponse::_Internal {
 public:
};

GetModelStatusResponse::GetModelStatusResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.GetModelStatusResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetModelStatusResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::tensorflow::serving::GetModelStatusResponse& from_msg)
      : model_version_status_{visibility, arena, from.model_version_status_},
        _cached_size_{0} {}

GetModelStatusResponse::GetModelStatusResponse(
    ::google::protobuf::Arena* arena,
    const GetModelStatusResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetModelStatusResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.GetModelStatusResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetModelStatusResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : model_version_status_{visibility, arena},
        _cached_size_{0} {}

inline void GetModelStatusResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetModelStatusResponse::~GetModelStatusResponse() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.GetModelStatusResponse)
  SharedDtor(*this);
}
inline void GetModelStatusResponse::SharedDtor(MessageLite& self) {
  GetModelStatusResponse& this_ = static_cast<GetModelStatusResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* GetModelStatusResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetModelStatusResponse(arena);
}
constexpr auto GetModelStatusResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(GetModelStatusResponse, _impl_.model_version_status_) +
          decltype(GetModelStatusResponse::_impl_.model_version_status_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(GetModelStatusResponse), alignof(GetModelStatusResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&GetModelStatusResponse::PlacementNew_,
                                 sizeof(GetModelStatusResponse),
                                 alignof(GetModelStatusResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetModelStatusResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetModelStatusResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetModelStatusResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetModelStatusResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetModelStatusResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetModelStatusResponse>(), &GetModelStatusResponse::ByteSizeLong,
            &GetModelStatusResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetModelStatusResponse, _impl_._cached_size_),
        false,
    },
    &GetModelStatusResponse::kDescriptorMethods,
    &descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetModelStatusResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> GetModelStatusResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tensorflow::serving::GetModelStatusResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1 [json_name = "model_version_status"];
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetModelStatusResponse, _impl_.model_version_status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1 [json_name = "model_version_status"];
    {PROTOBUF_FIELD_OFFSET(GetModelStatusResponse, _impl_.model_version_status_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::tensorflow::serving::ModelVersionStatus>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GetModelStatusResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.GetModelStatusResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.model_version_status_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetModelStatusResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetModelStatusResponse& this_ = static_cast<const GetModelStatusResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetModelStatusResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetModelStatusResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.GetModelStatusResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1 [json_name = "model_version_status"];
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_model_version_status_size());
               i < n; i++) {
            const auto& repfield = this_._internal_model_version_status().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.GetModelStatusResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetModelStatusResponse::ByteSizeLong(const MessageLite& base) {
          const GetModelStatusResponse& this_ = static_cast<const GetModelStatusResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetModelStatusResponse::ByteSizeLong() const {
          const GetModelStatusResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.GetModelStatusResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .tensorflow.serving.ModelVersionStatus model_version_status = 1 [json_name = "model_version_status"];
            {
              total_size += 1UL * this_._internal_model_version_status_size();
              for (const auto& msg : this_._internal_model_version_status()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetModelStatusResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetModelStatusResponse*>(&to_msg);
  auto& from = static_cast<const GetModelStatusResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.GetModelStatusResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_model_version_status()->MergeFrom(
      from._internal_model_version_status());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetModelStatusResponse::CopyFrom(const GetModelStatusResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.GetModelStatusResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetModelStatusResponse::InternalSwap(GetModelStatusResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.model_version_status_.InternalSwap(&other->_impl_.model_version_status_);
}

::google::protobuf::Metadata GetModelStatusResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace serving
}  // namespace tensorflow
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_tensorflow_5fserving_2fapis_2fget_5fmodel_5fstatus_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
