// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tensorflow/core/protobuf/device_filters.proto
// Protobuf C++ Version: 5.29.0

#include "tensorflow/core/protobuf/device_filters.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace tensorflow {

inline constexpr TaskDeviceFilters::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : device_filters_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TaskDeviceFilters::TaskDeviceFilters(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TaskDeviceFiltersDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaskDeviceFiltersDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaskDeviceFiltersDefaultTypeInternal() {}
  union {
    TaskDeviceFilters _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaskDeviceFiltersDefaultTypeInternal _TaskDeviceFilters_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR JobDeviceFilters_TasksEntry_DoNotUse::JobDeviceFilters_TasksEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : JobDeviceFilters_TasksEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : JobDeviceFilters_TasksEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct JobDeviceFilters_TasksEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JobDeviceFilters_TasksEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JobDeviceFilters_TasksEntry_DoNotUseDefaultTypeInternal() {}
  union {
    JobDeviceFilters_TasksEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JobDeviceFilters_TasksEntry_DoNotUseDefaultTypeInternal _JobDeviceFilters_TasksEntry_DoNotUse_default_instance_;

inline constexpr JobDeviceFilters::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : tasks_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR JobDeviceFilters::JobDeviceFilters(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JobDeviceFiltersDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JobDeviceFiltersDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JobDeviceFiltersDefaultTypeInternal() {}
  union {
    JobDeviceFilters _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JobDeviceFiltersDefaultTypeInternal _JobDeviceFilters_default_instance_;

inline constexpr ClusterDeviceFilters::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : jobs_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClusterDeviceFilters::ClusterDeviceFilters(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ClusterDeviceFiltersDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClusterDeviceFiltersDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClusterDeviceFiltersDefaultTypeInternal() {}
  union {
    ClusterDeviceFilters _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClusterDeviceFiltersDefaultTypeInternal _ClusterDeviceFilters_default_instance_;
}  // namespace tensorflow
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto = nullptr;
const ::uint32_t
    TableStruct_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::tensorflow::TaskDeviceFilters, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::tensorflow::TaskDeviceFilters, _impl_.device_filters_),
        PROTOBUF_FIELD_OFFSET(::tensorflow::JobDeviceFilters_TasksEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::tensorflow::JobDeviceFilters_TasksEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::tensorflow::JobDeviceFilters_TasksEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::tensorflow::JobDeviceFilters_TasksEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::tensorflow::JobDeviceFilters, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::tensorflow::JobDeviceFilters, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::tensorflow::JobDeviceFilters, _impl_.tasks_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::tensorflow::ClusterDeviceFilters, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::tensorflow::ClusterDeviceFilters, _impl_.jobs_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::tensorflow::TaskDeviceFilters)},
        {9, 19, -1, sizeof(::tensorflow::JobDeviceFilters_TasksEntry_DoNotUse)},
        {21, -1, -1, sizeof(::tensorflow::JobDeviceFilters)},
        {31, -1, -1, sizeof(::tensorflow::ClusterDeviceFilters)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::tensorflow::_TaskDeviceFilters_default_instance_._instance,
    &::tensorflow::_JobDeviceFilters_TasksEntry_DoNotUse_default_instance_._instance,
    &::tensorflow::_JobDeviceFilters_default_instance_._instance,
    &::tensorflow::_ClusterDeviceFilters_default_instance_._instance,
};
const char descriptor_table_protodef_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n-tensorflow/core/protobuf/device_filter"
    "s.proto\022\ntensorflow\"+\n\021TaskDeviceFilters"
    "\022\026\n\016device_filters\030\001 \003(\t\"\245\001\n\020JobDeviceFi"
    "lters\022\014\n\004name\030\001 \001(\t\0226\n\005tasks\030\002 \003(\0132\'.ten"
    "sorflow.JobDeviceFilters.TasksEntry\032K\n\nT"
    "asksEntry\022\013\n\003key\030\001 \001(\005\022,\n\005value\030\002 \001(\0132\035."
    "tensorflow.TaskDeviceFilters:\0028\001\"B\n\024Clus"
    "terDeviceFilters\022*\n\004jobs\030\001 \003(\0132\034.tensorf"
    "low.JobDeviceFiltersB\215\001\n\032org.tensorflow."
    "distruntimeB\023DeviceFiltersProtosP\001ZUgith"
    "ub.com/tensorflow/tensorflow/tensorflow/"
    "go/core/protobuf/for_core_protos_go_prot"
    "o\370\001\001b\006proto3"
};
static ::absl::once_flag descriptor_table_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto = {
    false,
    false,
    492,
    descriptor_table_protodef_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto,
    "tensorflow/core/protobuf/device_filters.proto",
    &descriptor_table_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto::offsets,
    file_level_enum_descriptors_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto,
    file_level_service_descriptors_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto,
};
namespace tensorflow {
// ===================================================================

class TaskDeviceFilters::_Internal {
 public:
};

TaskDeviceFilters::TaskDeviceFilters(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.TaskDeviceFilters)
}
inline PROTOBUF_NDEBUG_INLINE TaskDeviceFilters::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::tensorflow::TaskDeviceFilters& from_msg)
      : device_filters_{visibility, arena, from.device_filters_},
        _cached_size_{0} {}

TaskDeviceFilters::TaskDeviceFilters(
    ::google::protobuf::Arena* arena,
    const TaskDeviceFilters& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TaskDeviceFilters* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:tensorflow.TaskDeviceFilters)
}
inline PROTOBUF_NDEBUG_INLINE TaskDeviceFilters::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : device_filters_{visibility, arena},
        _cached_size_{0} {}

inline void TaskDeviceFilters::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TaskDeviceFilters::~TaskDeviceFilters() {
  // @@protoc_insertion_point(destructor:tensorflow.TaskDeviceFilters)
  SharedDtor(*this);
}
inline void TaskDeviceFilters::SharedDtor(MessageLite& self) {
  TaskDeviceFilters& this_ = static_cast<TaskDeviceFilters&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* TaskDeviceFilters::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TaskDeviceFilters(arena);
}
constexpr auto TaskDeviceFilters::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TaskDeviceFilters, _impl_.device_filters_) +
          decltype(TaskDeviceFilters::_impl_.device_filters_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(TaskDeviceFilters), alignof(TaskDeviceFilters), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TaskDeviceFilters::PlacementNew_,
                                 sizeof(TaskDeviceFilters),
                                 alignof(TaskDeviceFilters));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TaskDeviceFilters::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TaskDeviceFilters_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TaskDeviceFilters::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TaskDeviceFilters>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TaskDeviceFilters::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TaskDeviceFilters>(), &TaskDeviceFilters::ByteSizeLong,
            &TaskDeviceFilters::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TaskDeviceFilters, _impl_._cached_size_),
        false,
    },
    &TaskDeviceFilters::kDescriptorMethods,
    &descriptor_table_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TaskDeviceFilters::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 51, 2> TaskDeviceFilters::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tensorflow::TaskDeviceFilters>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string device_filters = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TaskDeviceFilters, _impl_.device_filters_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string device_filters = 1;
    {PROTOBUF_FIELD_OFFSET(TaskDeviceFilters, _impl_.device_filters_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\34\16\0\0\0\0\0\0"
    "tensorflow.TaskDeviceFilters"
    "device_filters"
  }},
};

PROTOBUF_NOINLINE void TaskDeviceFilters::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.TaskDeviceFilters)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_filters_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TaskDeviceFilters::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TaskDeviceFilters& this_ = static_cast<const TaskDeviceFilters&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TaskDeviceFilters::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TaskDeviceFilters& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:tensorflow.TaskDeviceFilters)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string device_filters = 1;
          for (int i = 0, n = this_._internal_device_filters_size(); i < n; ++i) {
            const auto& s = this_._internal_device_filters().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "tensorflow.TaskDeviceFilters.device_filters");
            target = stream->WriteString(1, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:tensorflow.TaskDeviceFilters)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TaskDeviceFilters::ByteSizeLong(const MessageLite& base) {
          const TaskDeviceFilters& this_ = static_cast<const TaskDeviceFilters&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TaskDeviceFilters::ByteSizeLong() const {
          const TaskDeviceFilters& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:tensorflow.TaskDeviceFilters)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string device_filters = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_device_filters().size());
              for (int i = 0, n = this_._internal_device_filters().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_device_filters().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TaskDeviceFilters::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TaskDeviceFilters*>(&to_msg);
  auto& from = static_cast<const TaskDeviceFilters&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.TaskDeviceFilters)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_device_filters()->MergeFrom(from._internal_device_filters());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TaskDeviceFilters::CopyFrom(const TaskDeviceFilters& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.TaskDeviceFilters)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TaskDeviceFilters::InternalSwap(TaskDeviceFilters* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.device_filters_.InternalSwap(&other->_impl_.device_filters_);
}

::google::protobuf::Metadata TaskDeviceFilters::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              JobDeviceFilters_TasksEntry_DoNotUse::JobDeviceFilters_TasksEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              JobDeviceFilters_TasksEntry_DoNotUse::JobDeviceFilters_TasksEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              JobDeviceFilters_TasksEntry_DoNotUse::JobDeviceFilters_TasksEntry_DoNotUse() : SuperType() {}
              JobDeviceFilters_TasksEntry_DoNotUse::JobDeviceFilters_TasksEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* JobDeviceFilters_TasksEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) JobDeviceFilters_TasksEntry_DoNotUse(arena);
              }
              constexpr auto JobDeviceFilters_TasksEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(JobDeviceFilters_TasksEntry_DoNotUse),
                                                          alignof(JobDeviceFilters_TasksEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull JobDeviceFilters_TasksEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_JobDeviceFilters_TasksEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &JobDeviceFilters_TasksEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<JobDeviceFilters_TasksEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &JobDeviceFilters_TasksEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &JobDeviceFilters_TasksEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(JobDeviceFilters_TasksEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &JobDeviceFilters_TasksEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* JobDeviceFilters_TasksEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> JobDeviceFilters_TasksEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JobDeviceFilters_TasksEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tensorflow::JobDeviceFilters_TasksEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .tensorflow.TaskDeviceFilters value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(JobDeviceFilters_TasksEntry_DoNotUse, _impl_.value_)}},
    // int32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JobDeviceFilters_TasksEntry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(JobDeviceFilters_TasksEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 key = 1;
    {PROTOBUF_FIELD_OFFSET(JobDeviceFilters_TasksEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .tensorflow.TaskDeviceFilters value = 2;
    {PROTOBUF_FIELD_OFFSET(JobDeviceFilters_TasksEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::tensorflow::TaskDeviceFilters>()},
  }}, {{
  }},
};

// ===================================================================

class JobDeviceFilters::_Internal {
 public:
};

JobDeviceFilters::JobDeviceFilters(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.JobDeviceFilters)
}
inline PROTOBUF_NDEBUG_INLINE JobDeviceFilters::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::tensorflow::JobDeviceFilters& from_msg)
      : tasks_{visibility, arena, from.tasks_},
        name_(arena, from.name_),
        _cached_size_{0} {}

JobDeviceFilters::JobDeviceFilters(
    ::google::protobuf::Arena* arena,
    const JobDeviceFilters& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  JobDeviceFilters* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:tensorflow.JobDeviceFilters)
}
inline PROTOBUF_NDEBUG_INLINE JobDeviceFilters::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : tasks_{visibility, arena},
        name_(arena),
        _cached_size_{0} {}

inline void JobDeviceFilters::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
JobDeviceFilters::~JobDeviceFilters() {
  // @@protoc_insertion_point(destructor:tensorflow.JobDeviceFilters)
  SharedDtor(*this);
}
inline void JobDeviceFilters::SharedDtor(MessageLite& self) {
  JobDeviceFilters& this_ = static_cast<JobDeviceFilters&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* JobDeviceFilters::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) JobDeviceFilters(arena);
}
constexpr auto JobDeviceFilters::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(JobDeviceFilters, _impl_.tasks_) +
          decltype(JobDeviceFilters::_impl_.tasks_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(JobDeviceFilters, _impl_.tasks_) +
          decltype(JobDeviceFilters::_impl_.tasks_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(JobDeviceFilters), alignof(JobDeviceFilters), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&JobDeviceFilters::PlacementNew_,
                                 sizeof(JobDeviceFilters),
                                 alignof(JobDeviceFilters));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull JobDeviceFilters::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_JobDeviceFilters_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &JobDeviceFilters::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<JobDeviceFilters>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &JobDeviceFilters::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<JobDeviceFilters>(), &JobDeviceFilters::ByteSizeLong,
            &JobDeviceFilters::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(JobDeviceFilters, _impl_._cached_size_),
        false,
    },
    &JobDeviceFilters::kDescriptorMethods,
    &descriptor_table_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* JobDeviceFilters::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 40, 2> JobDeviceFilters::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tensorflow::JobDeviceFilters>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(JobDeviceFilters, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(JobDeviceFilters, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // map<int32, .tensorflow.TaskDeviceFilters> tasks = 2;
    {PROTOBUF_FIELD_OFFSET(JobDeviceFilters, _impl_.tasks_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(JobDeviceFilters()._impl_.tasks_)>(
        0, 0, 0, 5,
        11)},
    {::_pbi::TcParser::GetTable<::tensorflow::TaskDeviceFilters>()},
  }}, {{
    "\33\4\0\0\0\0\0\0"
    "tensorflow.JobDeviceFilters"
    "name"
  }},
};

PROTOBUF_NOINLINE void JobDeviceFilters::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.JobDeviceFilters)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tasks_.Clear();
  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* JobDeviceFilters::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const JobDeviceFilters& this_ = static_cast<const JobDeviceFilters&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* JobDeviceFilters::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const JobDeviceFilters& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:tensorflow.JobDeviceFilters)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "tensorflow.JobDeviceFilters.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // map<int32, .tensorflow.TaskDeviceFilters> tasks = 2;
          if (!this_._internal_tasks().empty()) {
            using MapType = ::google::protobuf::Map<::int32_t, ::tensorflow::TaskDeviceFilters>;
            using WireHelper = _pbi::MapEntryFuncs<::int32_t, ::tensorflow::TaskDeviceFilters,
                                           _pbi::WireFormatLite::TYPE_INT32,
                                           _pbi::WireFormatLite::TYPE_MESSAGE>;
            const auto& field = this_._internal_tasks();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:tensorflow.JobDeviceFilters)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t JobDeviceFilters::ByteSizeLong(const MessageLite& base) {
          const JobDeviceFilters& this_ = static_cast<const JobDeviceFilters&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t JobDeviceFilters::ByteSizeLong() const {
          const JobDeviceFilters& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:tensorflow.JobDeviceFilters)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<int32, .tensorflow.TaskDeviceFilters> tasks = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_tasks_size());
              for (const auto& entry : this_._internal_tasks()) {
                total_size += _pbi::MapEntryFuncs<::int32_t, ::tensorflow::TaskDeviceFilters,
                                               _pbi::WireFormatLite::TYPE_INT32,
                                               _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void JobDeviceFilters::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JobDeviceFilters*>(&to_msg);
  auto& from = static_cast<const JobDeviceFilters&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.JobDeviceFilters)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.tasks_.MergeFrom(from._impl_.tasks_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JobDeviceFilters::CopyFrom(const JobDeviceFilters& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.JobDeviceFilters)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JobDeviceFilters::InternalSwap(JobDeviceFilters* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.tasks_.InternalSwap(&other->_impl_.tasks_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata JobDeviceFilters::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ClusterDeviceFilters::_Internal {
 public:
};

ClusterDeviceFilters::ClusterDeviceFilters(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.ClusterDeviceFilters)
}
inline PROTOBUF_NDEBUG_INLINE ClusterDeviceFilters::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::tensorflow::ClusterDeviceFilters& from_msg)
      : jobs_{visibility, arena, from.jobs_},
        _cached_size_{0} {}

ClusterDeviceFilters::ClusterDeviceFilters(
    ::google::protobuf::Arena* arena,
    const ClusterDeviceFilters& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ClusterDeviceFilters* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:tensorflow.ClusterDeviceFilters)
}
inline PROTOBUF_NDEBUG_INLINE ClusterDeviceFilters::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : jobs_{visibility, arena},
        _cached_size_{0} {}

inline void ClusterDeviceFilters::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ClusterDeviceFilters::~ClusterDeviceFilters() {
  // @@protoc_insertion_point(destructor:tensorflow.ClusterDeviceFilters)
  SharedDtor(*this);
}
inline void ClusterDeviceFilters::SharedDtor(MessageLite& self) {
  ClusterDeviceFilters& this_ = static_cast<ClusterDeviceFilters&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ClusterDeviceFilters::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ClusterDeviceFilters(arena);
}
constexpr auto ClusterDeviceFilters::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ClusterDeviceFilters, _impl_.jobs_) +
          decltype(ClusterDeviceFilters::_impl_.jobs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ClusterDeviceFilters), alignof(ClusterDeviceFilters), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ClusterDeviceFilters::PlacementNew_,
                                 sizeof(ClusterDeviceFilters),
                                 alignof(ClusterDeviceFilters));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ClusterDeviceFilters::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ClusterDeviceFilters_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ClusterDeviceFilters::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ClusterDeviceFilters>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ClusterDeviceFilters::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ClusterDeviceFilters>(), &ClusterDeviceFilters::ByteSizeLong,
            &ClusterDeviceFilters::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ClusterDeviceFilters, _impl_._cached_size_),
        false,
    },
    &ClusterDeviceFilters::kDescriptorMethods,
    &descriptor_table_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ClusterDeviceFilters::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ClusterDeviceFilters::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tensorflow::ClusterDeviceFilters>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .tensorflow.JobDeviceFilters jobs = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ClusterDeviceFilters, _impl_.jobs_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .tensorflow.JobDeviceFilters jobs = 1;
    {PROTOBUF_FIELD_OFFSET(ClusterDeviceFilters, _impl_.jobs_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::tensorflow::JobDeviceFilters>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ClusterDeviceFilters::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.ClusterDeviceFilters)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.jobs_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ClusterDeviceFilters::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ClusterDeviceFilters& this_ = static_cast<const ClusterDeviceFilters&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ClusterDeviceFilters::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ClusterDeviceFilters& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:tensorflow.ClusterDeviceFilters)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .tensorflow.JobDeviceFilters jobs = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_jobs_size());
               i < n; i++) {
            const auto& repfield = this_._internal_jobs().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:tensorflow.ClusterDeviceFilters)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ClusterDeviceFilters::ByteSizeLong(const MessageLite& base) {
          const ClusterDeviceFilters& this_ = static_cast<const ClusterDeviceFilters&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ClusterDeviceFilters::ByteSizeLong() const {
          const ClusterDeviceFilters& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:tensorflow.ClusterDeviceFilters)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .tensorflow.JobDeviceFilters jobs = 1;
            {
              total_size += 1UL * this_._internal_jobs_size();
              for (const auto& msg : this_._internal_jobs()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ClusterDeviceFilters::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ClusterDeviceFilters*>(&to_msg);
  auto& from = static_cast<const ClusterDeviceFilters&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.ClusterDeviceFilters)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_jobs()->MergeFrom(
      from._internal_jobs());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClusterDeviceFilters::CopyFrom(const ClusterDeviceFilters& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.ClusterDeviceFilters)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ClusterDeviceFilters::InternalSwap(ClusterDeviceFilters* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.jobs_.InternalSwap(&other->_impl_.jobs_);
}

::google::protobuf::Metadata ClusterDeviceFilters::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace tensorflow
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_tensorflow_2fcore_2fprotobuf_2fdevice_5ffilters_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
